kind: ConfigMap
apiVersion: v1
metadata:
  name: merlin-sessions-api-dev-config
  namespace: default
data:
  .env: |
    REDIS_IP_PORT=merlin-sessions-dev.y9zcam.clustercfg.memorydb.us-east-1.amazonaws.com:6379
    REDIS_PWD=
    DB_HOST=eventtracker-bd-develop.cluster-cba3qk5otxyc.us-east-1.rds.amazonaws.com
    DB_USER=eventtracker
    DB_PWD=YM2DyFU6H0hAEfd6QdHm
    DB_NAME=eventtracker
    API_KEY=QW93DLs6z39geUZmdpp6